config/routes.rb
GeekwiseNews::Application.routes.draw do
  get "home" => "home#index"
  
  resources :comments

  resources :posts

  resource :user, except: [:show]

  resource :session, only: [:new, :create, :destroy]

  get ":username" => "users#show", as: :profile

  get "upvote/:id" => "posts#upvote", as: :upvote
  get "downvote/:id" => "posts#downvote", as: :downvote
  get "commentup/:id" => "comments#commentup", as: :commentup
  get "commentdown/:id" => "comments#commentdown", as: :commentdown

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  has_many :comment_votes

  validates :content, length: { minimum: 2 }

  before_save :no_nil_points

  def cast_vote(points, user_id)
    CommentVote.create(comment_id: self.id, user_id: user_id)
    self.points += points
  end

private

  def no_nil_points
    self.points ||= 0 
  end
end

app/models/comment_vote.rb
class CommentVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment

  validates :user_id, uniqueness: { scope: [:comment_id] }
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :votes
  has_many :comments

  belongs_to :user

  URL_REGEX = /\A(http:\/\/|https:\/\/)\S+/

  validates :url, format: URL_REGEX
  validates :title, length: 2..80

  before_save :no_nil_points

  def cast_vote(points, user_id)
    Vote.create(post_id: self.id, user_id: user_id)
    self.points += points
  end

  def self.calculate_ranking
    posts = Post.all
    posts.each do |post|
      hours_elapsed = (DateTime.now.to_i - post.created_at.to_i).to_f / 3600
      post.rank = post.points.to_f / ((hours_elapsed + 2) ** 1.8)
      post.save
    end
  end

private

  def no_nil_points
    self.points ||= 0 
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts
  has_many :votes
  has_many :comments
  has_many :comment_votes
  
	attr_accessor :password

	before_save :encrypt_password

	validates :username, presence: true, uniqueness: true, format: /\A[\w]+\z/

	validates :password, length: { minimum: 6 }, format: /\d/, :if => :password_validatible?

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
private

  def password_validatible?
    password.present? || new_record?
  end

	def encrypt_password
		if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
	end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: [:post_id] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :logout, :pretty_url, :already_voted?, :already_voted_comment?

  def login_as(user)
    session[:user_id] = user.id
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by(:id => session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def logout
    session.delete(:user_id)
  end

  def authenticate_user!
    redirect_to new_session_url unless logged_in?
  end

  def pretty_url(url)
    url.slice! "http://"
    url.slice! "https://"
    url.slice! "www."
    url
  end

  def already_voted?(post_id, user_id)
    Vote.exists?(post_id: post_id, user_id: user_id)
  end

  def already_voted_comment?(comment_id, user_id) 
    CommentVote.exists?(comment_id: comment_id, user_id: user_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :authenticate_user!, except: [:show]
  before_action :set_comment, only: [:commentup, :commentdown]

  def create
    if comment = current_user.comments.create(comment_params)
      redirect_to post_url(comment.post_id)
    else
      render 'show'  
    end
  end

  def commentup
    @comment.cast_vote(1, current_user.id)
    @comment.save
    redirect_to post_url(@comment.post_id)
  end

  def commentdown
    @comment.cast_vote(-1, current_user.id)
    @comment.save
    redirect_to post_url(@comment.post_id)
  end

private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    Post.calculate_ranking
    @posts = Post.order("rank DESC, created_at DESC").page(params[:page]).per(10)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_post, only: [:upvote, :downvote, :show]

  def new
    @post = Post.new
  end

  def show
    @comment = Comment.new
  end

  def create
    if current_user.posts.create(post_params)
      redirect_to home_url, notice: 'Post was successfully created.'
    else
      render 'new' 
    end
  end

  def upvote
    @post.cast_vote(1, current_user.id)
    @post.save
    if params[:redirect] == "comments"
      redirect_to post_url(@post.id)
    else
      redirect_to home_url
    end
  end

  def downvote
    @post.cast_vote(-1, current_user.id)
    @post.save
    if params[:redirect] == "comments"
      redirect_to post_url(@post.id)
    else
      redirect_to home_url
    end
  end

private

    def set_post
      @post = Post.find(params[:id])  
    end

    def post_params
      params.require(:post).permit(:title, :url, :user_id, :points)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, except: [:destroy]

  def create
    if user = User.authenticate(params[:username], params[:password])
      login_as(user)
      redirect_to home_url
    else
      flash.now[:alert] = "Invalid username or password!"
      render "new"
    end
  end

  def destroy
    if logged_in?
      logout
      redirect_to home_url
    else  
      redirect_to new_session_url
    end
  end

private

  def redirect_if_logged_in
    redirect_to home_url if logged_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      login_as(@user)
      redirect_to home_url, notice: 'User was successfully created.'
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to edit_user_url, notice: "Attributes updated succesfully"
    else
      render "edit"
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    redirect_to home_index_url
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<%= link_to @post.title, @post.url, target: 'blank' %> <span class="url">(<%= pretty_url(@post.url) %>)</span><br />
<span class="subscript"><%= @post.points %> points by <%= @post.user.username %> <%= time_ago_in_words(@post.created_at) %> ago | <%= link_to "#{@post.comments.count} comments", comment_path(@post.id) %></span>

<% if current_user %>
  <div class="form">
    <%= form_for(@comment) do |f| %>
      <%= f.hidden_field :post_id, value: @post.id %>
      <%= f.text_area :content %>
      <%= f.submit %>
    <% end %>
  </div>
<% end %>

<br />
<br />

<% @post.comments.each do |comment| %>
  <div class="comment">
    <span class="subscript"><%= comment.user.username %> <%= time_ago_in_words(comment.created_at) %> ago</span><br />
    <span class="content"><%= comment.content %></span>
  </div><br />
<% end %>

app/views/home/index.html.erb
<h1>Posts</h1>
<ol>
  <% @posts.each do |post| %>
    <li class="post">
      <%= link_to post.title, post.url, target: 'blank' %> <span class="url">(<%= pretty_url(post.url) %>)</span>
      <% if current_user && !already_voted?(post.id, current_user.id) %>
        <%= link_to image_tag("arrow_down.png", height: "12"), downvote_url(post.id), title: "Down vote" %>
        <%= link_to image_tag("arrow-up.png", height: "12"), upvote_url(post.id), title: "Up vote" %>
      <% end %>
      <br />
      <span class="subscript"><%= post.points %> points by <%= post.user.username %> <%= time_ago_in_words(post.created_at) %> ago | 
        <%= link_to "#{post.comments.count} comments", post_path(post.id) %></span>
    </li>
  <% end %>
  <br />
  <br />
  <%= paginate @posts %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geekwise News</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar">
  <ul class="nav-left">
    <li class="brand"><%= image_tag "geekwise.png" %><span> Geekwise News</span></li>
    <li><%= link_to "Home", home_url %></li>
    <% if logged_in? %>
      <li><%= link_to "New Post", new_post_path %></li>
    <% end %>
  </ul>
  <ul class="nav-right">
    <% if logged_in? %>
      <li>Welcome, <%= link_to current_user.username, profile_path(current_user.username) %></li>
      <li><%= link_to "Settings", edit_user_path %></li>
      <li><%= link_to "Logout", session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign Up", new_user_path %></li>
      <li><%= link_to "Login", new_session_path %></li>
    <% end %>
  </ul>
</nav>

<div class="main-content">
  <% if flash[:notice] %>
    <div class="flash notice"><%= flash[:notice] %></div>
  <% end %>

  <% if flash[:alert] %>
    <div class="flash alert"><%= flash[:alert] %></div>
  <% end %>

  <%= yield %>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class="container">
  <h1 style="text-align: center;">New Post</h1>
  <div class="form">
    <%= form_for(@post) do |f| %>
      <div class="form-inputs">
        <%= f.text_field :title, class: "form-control", placeholder: "Enter a title for your post" %>
        <%= f.text_field :url, class: "form-control", placeholder: "Enter url (Must have http://)" %>    
      </div> 
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<h1>Comments</h1>
<%= link_to @post.title, @post.url, target: 'blank' %> <span class="url">(<%= pretty_url(@post.url) %>)</span>
<% if current_user && !already_voted?(@post.id, current_user.id) %>
  <%= link_to image_tag("arrow_down.png", height: "12"), downvote_url(@post.id, redirect: "comments"), title: "Down vote" %>
  <%= link_to image_tag("arrow-up.png", height: "12"), upvote_url(@post.id, redirect: "comments"), title: "Up vote" %>
<% end %>
<br />
<span class="subscript"><%= @post.points %> points by <%= @post.user.username %> <%= time_ago_in_words(@post.created_at) %> ago | <%= link_to "#{@post.comments.count} comments", post_path(@post.id) %></span>

<% if current_user %>
  <div class="form">
    <%= form_for(@comment) do |f| %>
      <%= f.hidden_field :post_id, value: @post.id %>
      <%= f.text_area :content %>
      <%= f.submit %>
    <% end %>
  </div>
<% end %>

<br />
<br />

<% @post.comments.each do |comment| %>
  <div class="comment">
    <span class="subscript"><%= comment.points %> points by <%= comment.user.username %> <%= time_ago_in_words(comment.created_at) %> ago</span>
    <% if current_user && !already_voted_comment?(comment.id, current_user.id) %>
      <%= link_to image_tag("arrow_down.png", height: "12"), commentdown_url(comment.id), title: "Down vote" %>
      <%= link_to image_tag("arrow-up.png", height: "12"), commentup_url(comment.id), title: "Up vote" %>
    <% end %>
    <br />
    <span class="content"><%= comment.content %></span>
  </div><br />
<% end %>

app/views/shared/_errors.html.erb
<% if record.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(record.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% record.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <%= render "shared/errors", record: @user %>
  <div class="form">
    <%= form_for(@user, url: user_path) do |f| %>
      <div class="form-inputs">
        <%= f.text_field :username, placeholder: "Enter a username", class: "form-control" %>
        <%= f.password_field :password, placeholder: "Enter a password", class: "form-control" %>
      </div> 
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form'%>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>